### ISSUE TITLE
StyleCheck: "Variable is never used" on method call without parenthesis

### ISSUE THREAD

**Issue by Andy-FW** [dlang-community/D-Scanner#182]
If you call a method from a class instance without the parenthesis, --styleCheck will show a warning that the variable of your class instance is never used.

Here is a short snippet:

void main()
{
    auto test = new Test;
    test.start;
}

class Test
{
    void start()
    {
        // Do nothing
    }
}

**Comment by MWumpusZ** [comment]
Irrespective of whether leaving away the parentheses is "abuse" of the syntax, surely `test.start` *is* a use of `test`.
The syntax may suggest it is not a *useful* use of `test`, i.e. that a "warning: statement with no effect" may apply, but as long as that statement is present, `test` is being used.

Or am I missing a case which is hard to distinguish from this one, where `test` really would not be in use?

**Comment by Basile-z** [comment]
Adding the warning you suggest is not reasonable. All people who don't use parens to call function without parameters would complain.

**Comment by belka-ew** [comment]
I can't reproduce this since 0.5.11, at least not with the code above. The last version producing the error is 0.5.10.

**Comment by Basile-z** [comment]
indeed.
