### ISSUE TITLE
Could ASTNode get a pointer to it's parent in the tree ?

### ISSUE THREAD

**Issue by UplinkCoder** [dlang-community/D-Scanner#184]
Well,
I am in the process of writing a tool for source-to-source-translation with D.
When I use the ASTVisitor it's hard to know where I am in the tree.
If the ASTNode could be extended to point to it's parent in the tree that would be most helpful.
Or is there some method to get this Information ?

**Comment by BBasile** [comment]
This was for libdparse. Also you're certainly much further now.
