### ISSUE TITLE
Abstract final classes without parent must match `Type` casing

### ISSUE THREAD

**Issue by simendsjo** [dlang-community/D-Scanner#199]
An abstact final class without a parent is pretty much just a value, and it should be possible to name it as such. (See the class `environment` in `std.process`).

**Comment by BBasile** [comment]
D-Scanner cannot necessarily recognize that the intention is to use a class in a certain way.
For this case i recommend this idiom:

```d
final class MostlyStaticThingsInside {}
alias likeAnInstance = MostlyStaticThingsInside;
```
