### ISSUE TITLE
DIP 74 Checks

### ISSUE THREAD

**Issue by Hackerpilot** [dlang-community/D-Scanner#233]
http://wiki.dlang.org/DIP74
- Warn when only one of `opAddRef` or `opRelaese` is present
- Warn when `opAddRef` or `opRelaese` is `const`
- Warn when `opAddRef` or `opRelaese` is not marked `nothrow final`

**Comment by BBasile** [comment]
I think that DIP74 can be officially declared dead ? :latin_cross: 
AFAIK, RC will be done, if ever at a library level

**Comment by wilzbach** [comment]
> AFAIK, RC will be done, if ever at a library level

Yep, I think the plan is to make `core.rc` a thing (it's planned for this to happen this year ...)
