### ISSUE TITLE
Add check for unions and @safe

### ISSUE THREAD

**Issue by jcrapuchettes** [dlang-community/D-Scanner#264]
Functions and methods should not be allowed to be marked `@safe` if they are working with a union.

**Comment by wilzbach** [comment]
Isn't this something that the safety feature of the D compiler should warn you of?

**Comment by ZombineDev** [comment]
I think this can be closed since dmd already emits errors if you try to access union members where one of them is/has an indirection.

**Comment by wilzbach** [comment]
Yes my point :)
