### ISSUE TITLE
Statically check writef formats

### ISSUE THREAD

**Issue by mfalda** [dlang-community/D-Scanner#273]
It would be useful to detect `writef` format problems at compile time (through Dscanner). 
### Possible motivation

DMD v2.067.1 is not able to detect at compile time the errors in the example code below; I did not try GDC nor LDC; clang 3.5.0-10 instead warns about all of them. With DMD sometimes a FormatException is catched, however the output is rather obscure: The following message refers to bug 3 or bug 5?

```
Wrong format: std.format.FormatException@c:\D\dmd2\windows\bin\..\..\src\phobos\std\format.d(1431): integral
----------------
0x00403831
0x0040350C
0x00402458
0x0040217A
0x004020D6
0x00402062
0x00408DB6
0x00408D8B
0x00408CA3
0x00406AA0
0x7606337A in BaseThreadInitThunk
0x76F992E2 in RtlInitializeExceptionChain
0x76F992B5 in RtlInitializeExceptionChain
```

``` D
import std.stdio;

void main() 
{
    try {
          writefln("Too few!", 5); // bug 1
          writefln("Too much: %d!"); // bug 2
          writefln("Wrong format: %c!", 5); // bug 3
                  writefln("Wrong format: %s!", 5); // bug 4
          writefln("Wrong format: %d!", "a");    // bug 5
    }
    catch (Exception e) { // here just bugs 2 and 3 and 5 are catched!
        writeln(e);
    }
}
```

**Comment by CyberShadow** [comment]
+1 (also for `format`, `formattedWrite` and `writefln`)

**Comment by CyberShadow** [comment]
OK, I couldn't wait so I did it myself:

https://github.com/Hackerpilot/Dscanner/commit/70c1fda894aae2fbb456aaf2a2cfa24bab3ad484

The reason I needed this was that in D1, `format` would just tack on extra arguments to the end of the string, like `std.conv.text` does. In D2, trying to do that throws an exception at runtime. I was porting a lot of D1 code, and a lot of error messages were formatted using `format`, and were covered very poorly by tests - which caused some obscure/unusual conditions to throw exceptions when the program attempted to log them.

Uncovered one more bug using this.

**Comment by mfalda** [comment]
Thank you very much. I checked the new version and now it is possible to catch bugs 1 and 2 of my original example. I discovered that bug 4 is not a real bug: the D language will interpret "%s" placeholder as the string representation of the corresponding variable.
Now bugs 3 and 5 should be addressed. I think that I should study libdparser to be able to contribute. In any case, I would add a function like the one below to check the soundness of the format arguments. Note that the "default" statement is a rough way to check the [format grammar](http://dlang.org/phobos/std_format.html#.formattedWrite): If I am not wrong DMD does not check it and, for example, this statement throws again a run-time exception!
```D
 writefln("What does 'z' mean? %z!", 5);
```
---

```D

private bool check_format(TypeInfo t)  // the typeid of a format argument
{
	t = t.toLower();
	switch (t) {
		case 'c':
			return (t == typeid(char) || t == typeid(dchar) || t == typeid(wchar));
		case 'b':
		case 'd':
		case 'o':
		case 'x':
			return (t == typeid(int) || t == typeid(uint)); // etc ... a smarter way to check an integral type?
		case 'e':
		case 'g':
		case 'f':
		case 'a':
			return (t == typeid(float) || t == typeid(double));			
		case 's':
			return true;
		default:
			return false; // format specifier not allowed
	}
}
```

**Comment by mfalda** [comment]
Sorry: The correct prototype of my function would be:

```D
// t is the format argument being checked
// type is the typeid of a format argument
private bool check_format(char t,  TypeInfo type)
```

This function could be an additional member of the class "FormatStringCheck" in the file "format_string.d"

**Comment by CyberShadow** [comment]
Yep. But I don't think Dscanner tracks the types of declarations.

If we ever get to that point, we could use `FormatSpec` from `std.format` to parse the format string, instead of parsing it by hand again.

**Comment by mfalda** [comment]
I close this issue since, if I am not wrong, we have reached the limits of the underlying syntactic parser. I hope that such semantics validations will be implemented directly in the core D2, in order to have a language with a truly strong static type system able to minimize the occurrence of run-time exceptions as far as possible; like F# or Haskell.

**Comment by CyberShadow** [comment]
I think it is useful even if it is not perfect, please reopen.

**Comment by wilzbach** [comment]
Since 2.074.0 this is supported directly by Phobos if the format string is passed in as template argument, see e.g.:

https://dlang.org/changelog/2.074.0.html#std-format-formattedWrite
