### ISSUE TITLE
Stop warning about length subtraction when encapsulated

### ISSUE THREAD

**Issue by JackStouffer** [dlang-community/D-Scanner#308]
I'm not sure this is even possible, but if it is can dscanner stop giving the warning `Avoid subtracting from '.length' as it may be unsigned.` when

```
auto a = b.length - 1;
```

is changed to

```
auto a = b.length == 0 ? 0 : b.length - 1;
```

or something similar.

**Comment by Sandman83** [comment]
e. g. I have an in contract, which is 
....
```
in
{
    assert(!b.empty); 
}
body
{
    // here it would be nice to subtract from the length without any warning... if possible...
}
```

**Comment by BBasile** [comment]
I agree that this warning can be annoying but it's hard to check accurately, let's say (i tried), if length is tested before. The best is solution is to disable it in you config file
