### ISSUE TITLE
spurious warnings about non-const toString inside const {} block

### ISSUE THREAD

**Issue by dhasenan** [dlang-community/D-Scanner#312]
``` D
class Foo {
  const {
    override string toString() { return "foo"; }
  }
}
```

produces the message:

consttostring.d(3:22)[warn]: Methods 'opCmp', 'toHash', 'opEquals', 'opCast', and/or 'toString' are non-const.

**Comment by Hackerpilot** [comment]
Related: https://github.com/Hackerpilot/DCD/issues/289
