### ISSUE TITLE
'never used' is incorrectly reported when mixins are used

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-Scanner#326]
When mixins are used, they should be expanded before `never used` is reported. 
See this simple example:

```
/// ga
enum ga = q{a++};

/// doc foc
void foo(int a)
{
    mixin(ga);
}

/// doc main
void main()
{
    foo(1);
}
```

**Comment by Hackerpilot** [comment]
The libraries that D-Scanner is built on don't do any mixin expansion, so don't expect this any time soon.

**Comment by BBasile** [comment]
I think that 2 years after you should understand more the limiation of dparse Seb so i close.

**Comment by ntrel** [comment]
Should this really be closed? When dmd as a library works, can't this be implemented?
