### ISSUE TITLE
Doesn't build using dub (master & latest release)

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/D-Scanner#350]
``` d
src/analysis/lambda_return_check.d(40,29): Error: no property 'line' for type 'const(FunctionLiteralExpression)'
src/analysis/lambda_return_check.d(40,40): Error: no property 'column' for type 'const(FunctionLiteralExpression)'
```

Happens on fedora, archlinux and windows 10 (vm). Don't forget to run `dub upgrade` to ensure dub uses the specified packages (it will always choose those on fresh systems/installs)

**Comment by wilzbach** [comment]
Try to build it with the makefile - I think it's a known error.

**Comment by wilzbach** [comment]
> the specified packages (it will always choose those on fresh systems/installs)

that's why the dub.selections.json should always be added to git ;-)

**Comment by Hackerpilot** [comment]
Those `line` and `column` fields were added to libdparse in version 0.7.0-alpha10. D-Scanner's dub.json specifies a dependency on 0.7.0-alpha11 or later. I don't know why Dub is getting this wrong.

**Comment by MartinNowak** [comment]
> Those line and column fields were added to libdparse in version 0.7.0-alpha10. D-Scanner's dub.json specifies a dependency on 0.7.0-alpha11 or later. I don't know why Dub is getting this wrong.

Because you're using a wobbly version specification (`~>0.7.0-alpha11`), i.e. anything 0.7.0-ish.
But there also seems to be an issue with dub that can't resolve `"libdparse": "==0.7.0-alpha11"` from dscanner and `"libdparse": ">=0.7.0-alpha9 <0.8.0"` from dsymbol.

**Comment by WebFreak001** [comment]
Fixed a while ago
