### ISSUE TITLE
Build failure on KDE Linux Mint

### ISSUE THREAD

**Issue by Tafnab** [dlang-community/D-Scanner#354]
After running recursive git update, I make and get the following error:

libdparse/src/dparse/lexer.d(2246): Error: found 'pure' when expecting '{'
followed by a bunch of mismatched curly braces errors. The curly braces are fine. 

Is this a complaint that dmd doesn't know where the assembler is or some such conflict?

**Comment by Hackerpilot** [comment]
Are you using a front-end version older than 2.067?

**Comment by Tafnab** [comment]
Command line git.  Using dmd, if that matters.

**Comment by Tafnab** [comment]
Git version 1.9.1, Linux Mint repo.

**Comment by wilzbach** [comment]
what does

```
dmd --version
```

say?

**Comment by Tafnab** [comment]
DMD64  v2.066.1

**Comment by wilzbach** [comment]
See:

> Are you using a front-end version older than 2.067?

This version is very old - is this your distributions package?
See this page for instructions how to upgrade: http://dlang.org/download.html

**Comment by Tafnab** [comment]
Excellent! Now to hook it into things.

**Comment by BBasile** [comment]
Assuming

> Excellent!

meant _"got it to compile"_ and then closing.
