### ISSUE TITLE
False Negative for Unmodified Variable

### ISSUE THREAD

**Issue by JackStouffer** [dlang-community/D-Scanner#367]
From std.uni, line 1122

```
    private void simpleWrite(TypeOfBitPacked!T val, size_t n)
    in
    {
        static if (isIntegral!T)
            assert(val <= mask);
    }
    body
    {
        auto q = n / factor;
        auto r = n % factor;
        size_t tgt_shift = bits*r;
        size_t word = origin[q];
        origin[q] = (word & ~(mask<<tgt_shift))
            | (cast(size_t)val << tgt_shift);
    }
```

dscanner correctly states that `r` can be `immutable`, but it does not say that `q` can as well.

**Comment by Hackerpilot** [comment]
I might have done that to reduce false positives because variables used as indexes can actually be passed by non-const ref to an opIndex function.

**Comment by BBasile** [comment]
Actually the comment you stroke out is right. If you fix the check so that this case is detected then people will complain that there's a false positive since they can't pass a const variable to their opIndex !
