### ISSUE TITLE
Allow custom formats of output errors

### ISSUE THREAD

**Issue by lenormf** [dlang-community/D-Scanner#377]
Hi,

I'd like to be able to format the errors printed when checking D files in the following manner:
```
{filename}:{line}:{column}: {kind}: {message}
```

Could this be possible, with a command line flag and/or a configuration file option?

Thanks.

**Comment by BBasile** [comment]
I guess you want this feature because a particular editor doesn't allow you to click the messages produced by D-Scanner ?

**Comment by lenormf** [comment]
I'm trying to integrate D-Scanner as an external syntaxic check tool into [kakoune](https://github.com/mawww/kakoune), yes.
