### ISSUE TITLE
add a --skipPhobosChecks switch

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#406]
With the recent additions related to phobos a lot of noise is generated for the import sortedness and the unittest annotations. To disable them a config file is required. To continue using dscanner without config file this switch seems necessary. (this was also the idea behind the --slipTests switch).

So this switch would disable the checks made especially for phobos CI.

**Comment by wilzbach** [comment]
> With the recent additions related to phobos a lot of noise is generated for the import sortedness and the unittest annotations. To disable them a config file is required. To continue using dscanner without config file this switch seems necessary. 

These checks could also be disabled by default, then no switch would be necessary (KISS!)

**Comment by BBasile** [comment]
Yes better. I'd go for this option.
