### ISSUE TITLE
Warn about applying @trusted to an entire template

### ISSUE THREAD

**Issue by JackStouffer** [dlang-community/D-Scanner#425]
This is often a hole in `@safe` code, as unsafe code could be easily called via operator overloads or any numerous other ways. The safer method is to use trusted escapes.

This maybe overkill, so some possible concessions:

* Don't issue the warning for templates which are not very complex
* Only issue the warning when the template has no template constraints.

**Comment by BBasile** [comment]
Sounds like an easy addition. Two questions:

- What's the declaration count threshold (inside the template) ?
- Does the check also apply to the parametric aggregates or is it restricted to `template`

About the constraints, i don't see the utility. A constraint does not prevent the problem.

**Comment by BBasile** [comment]
can be done with #545
