### ISSUE TITLE
Ignore warnings on parameters named "_"

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/D-Scanner#490]
```d
auto cb = delegate(size_t) {}; // dmd error: type void is inferred from initializer delegate (size_t)
```
adding a variable name to the argument fixes it but now dscanner gives a warning:
```d
auto cb = delegate(size_t _) {}; // dscanner warning: Parameter _ is never used.
```

**Comment by BBasile** [comment]
Off topic but wasn't the issue more the fact that you forgot the delegate type ?

```d
auto cb = void delegate(size_t) {};
```

**Comment by WebFreak001** [comment]
@BBasile that doesn't even compile for me:
```
a.d(1): Error: found 'delegate' when expecting '.' following void
a.d(1): Error: found '(' when expecting identifier following 'void.'
a.d(1): Error: semicolon expected following auto declaration, not 'size_t'
a.d(1): Error: found ')' when expecting ';' following statement
```

**Comment by WebFreak001** [comment]
I guess it's not a false positive but there is no possible fix so I wouldn't show an error

**Comment by BBasile** [comment]
Ah okay i see now that it wasn't a type definition. why not just auto `cb = (size t){}`;

**Comment by WebFreak001** [comment]
Same issue, try running what you send with `rdmd --eval='auto cb = (size_t) {};'` before you comment :p

**Comment by BBasile** [comment]
Ah it things it's a variable name...

**Comment by BBasile** [comment]
Anyway, the parameter is never used, as indicated. Try
```d
void main()
{
    const cb = delegate(size_t t) {return t + 1;};
    cb(1);
}
```
And no warnings.

**Comment by WebFreak001** [comment]
well but I can't use the parameter and there is no way to disable it just for that line in dscanner, so it's always giving me warnings I don't want to read. Why not add some way to mark it as used?

**Comment by wilzbach** [comment]
Ah sorry - I was catching up with my GH notifications and didn't see the merged PR. Nice work, @WebFreak001
