### ISSUE TITLE
Undocumented check should ignore deprecated symbols

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-Scanner#492]
See: https://github.com/dlang/phobos/pull/5545

The `deprecated` symbol might be undocumented on purpose.

**Comment by WebFreak001** [comment]
I think this is fixed, in ~master this code works without warnings:
```d
/// C
class C {
	private int a;
	deprecated int b;
	override void foo() {}
	deprecated("use foo instead") void bar() {}
}
```

**Comment by BBasile** [comment]
Or maybe the report was invalid in first place. If you look at CircleCI status in the phobos PR linked above it passed.

**Comment by BBasile** [comment]
So you can close this one without PR.
