### ISSUE TITLE
False default initializer when initializing with ""

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/D-Scanner#501]
```d
string a;
writeln(a is null); // true
string b = ""; // initializer is useless
writeln(b is null); // false
string c = null; // nothing
writeln(c is null); // true
```
As seen here `a` is null by default ant not `""`, so the initializer warning is showing wrong information

**Comment by BBasile** [comment]
which one ? `b` or `c` declaration ?

**Comment by WebFreak001** [comment]
sorry, updated the example & title to properly reflect the issue now

**Comment by BBasile** [comment]
But here the logic is more
```d
string a = "";
assert(a == a.init);
string b = null;
assert(b == b.init); 
string c = [];
assert(c == c.init);
```

The only problem is then b, that's not detected.

**Comment by WebFreak001** [comment]
`==` is not the same as `is`, it doesn't work that way for initializing/checking with null

**Comment by BBasile** [comment]
I disagree. `string a = ""` is clearly a useless initializer. so invalid.
