### ISSUE TITLE
Exclude path argument?

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#530]
For the company I work, I preparing a XMake plugin for D. There is a rule, XMake plugins are not allowed to access the internet. Therefore the D (Dub) projects have to bring all dependencies with them. See attached example. There is a folder "dependencies" which has e.g. d-unit.
[dlang-sample.zip](https://github.com/dlang-community/D-Scanner/files/1455318/dlang-sample.zip)

While executing D-Scanner, most of the findings are regarding the dependencies and not the actual project itself. I wonder whether you can add an "exclude path" which can be used to exclude folders from linting.

**Comment by BBasile** [comment]
You can do this by adding a dscanner.ini file in the project root and set the exclusions for rach check: https://github.com/dlang-community/D-Scanner#selecting-modules-for-a-specific-check

**Comment by andre2007** [comment]
yes, that solves my issue. Thanks a lot.
