### ISSUE TITLE
D-Scanner release binaries

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#531]
I would like to run D-Scanner for D (Dub) projects in a build infrastructure (XMake). To have reproducable builds, the XMake plugins are not allowed to access the internet. The dub projects have all dependencies locally and during dub build I set the --skip-registry=all flag. 

While running dub fetch dscanner && dub run dscanner Dub dependencies are retrieved to build D-Scanner. If the dub project which should be built also has the same dependency like D-Scanner the build violates the "reproducable builds rule".

Could you provide from time to time binaries for the major operation systems windows, linux, OS2?

**Comment by BBasile** [comment]
This done for linux since recently (see the [assets for 0.5.0](https://github.com/dlang-community/D-Scanner/releases/tag/v0.5.0) for example.

**Comment by andre2007** [comment]
The linux binary together with docker solves my issue. Thanks a lot.

**Comment by wilzbach** [comment]
BTW we setup an automatic deployment to dockerhub if that's interesting to you
That's fairly easy. Essentially this would mean adding a `Dockerfile` + these two lines once:

https://github.com/dlang-tour/core/blob/master/.travis.yml#L48
