### ISSUE TITLE
Add a check that warns about mass-applied attributes

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-Scanner#545]
From https://github.com/dlang/phobos/pull/6010

tl;dr: this should be forbidden:

```d
@trusted:
```

**Comment by stefan-koch-sociomantic** [comment]
why ? in certain cases it is legitimate,

**Comment by stefan-koch-sociomantic** [comment]
darn posted with the wrong account again ;-/

**Comment by wilzbach** [comment]
See the Phobos PR for a motivation. 
This is one of those checks that won't be activated by default, but can be toggled on for people who want to restrict certain "features" in their codebase.

**Comment by stefan-koch-sociomantic** [comment]
I agree with `@trusted` being bad.
others not so much.

**Comment by skl131313** [comment]
Maybe more specifically mass applying `@trusted`? There isn't as big of a problem with other attributes, but `@trusted` is unsafe. I'd say even doing `@trusted:` anywhere, even in a class/struct should not be allowed.

**Comment by BBasile** [comment]
applied to a whole template too, #425

**Comment by BBasile** [comment]
The PR is focused on `@trusted`, which was also the request of #425.
