### ISSUE TITLE
~master, infinite loop with -S and std.traits

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#554]
Maybe due to my last PR.

**Comment by BBasile** [comment]
dcd-server too so it's a libdparse bug.

**Comment by BBasile** [comment]
if you delete from the end, last line of code triggering the bug is line 1723 in std.traits (~master)
`static assert(!hasFunctionAttributes!(ref_property, "@property", "ref", "@safe", "@nogc"));`

**Comment by wilzbach** [comment]
FYI: we don't run D-Scanner at the moment at Phobos as it's SEGFAULTing in the GC

https://github.com/dlang/phobos/pull/5929#issuecomment-352187837

The SEGFAULT is reproducible, but so far only on CircleCi.

**Comment by BBasile** [comment]
this is something else that impacts people using ~master version of D-Scanner and DCD. I just left notes in the report when i find something new.

**Comment by BBasile** [comment]
Well i'll open in dparse. Can reproduce it there from now.
