### ISSUE TITLE
Dscanner should allow opCmp with no toHash

### ISSUE THREAD

**Issue by JackStouffer** [dlang-community/D-Scanner#575]
Consider

```d
struct S
{
        int opCmp(S rhs)
        {
            assert(0);
        }
}

void main()
{
        assert(S.init == S.init);
}
```

The absence of opEquals means it's using the language default, which means it's safe for S to use the default toHash as well.

dscanner should only throw a warning when opEquals exists but toHash doesn't.

**Comment by Hackerpilot** [comment]
I agree that this would be a good change.
