### ISSUE TITLE
DScanner dockerfile on Docker Hub

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#591]
Do you already considered to provide a dockerfile on Docker Hub which allows to scan a project on a host system without a D / D-Scanner installation?

Use case is CI Systems like Jenkins(Pipelines) which clones git repositories and execute static code checks  on the projects.  In your pipeline you can execute docker (pseudo code example below) to scan your project. After the scan, the project dir will contain the D-Scanner result file. 

docker run -v ~/dProject:/data D-Scanner:latest -rm dscanner -s --report > report.json

An official docker hub repository from dlang-community would be quite convenient.

**Comment by wilzbach** [comment]
Sure why not -> an initial attempt: https://github.com/dlang-community/D-Scanner/pull/592

**Comment by andre2007** [comment]
This issue is solved.
