### ISSUE TITLE
Case of false positive for identical LHS and RHS

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#593]
```d
static if (is(T == const U, U) || is(T == immutable U, U))
{}
```

**Comment by BBasile** [comment]
It was reported here: https://forum.dlang.org/thread/p9tmpg$1igb$1@digitalmars.com but i cannot reproduce the problem.

**Comment by wilzbach** [comment]
I can confirm that this happens semi-regularly on Phobos's CircleCi, e.g. https://circleci.com/gh/dlang/phobos/7306

However, I haven't managed to reproduce it locally either :/

**Comment by BBasile** [comment]
cool an Heisenbug... :ghost:

**Comment by Hackerpilot** [comment]
This is probably something in libdparse.

**Comment by Hackerpilot** [comment]
Specifically we should review the `generateOpEquals` code in src/dparse/ast.d.

**Comment by BBasile** [comment]
`colonLocation` maybe. There might be other props that should not be compared. Once was `comment`.

**Comment by BBasile** [comment]
oops no, colon is no involve here, it's comma.

**Comment by BBasile** [comment]
Another occurence: https://circleci.com/gh/dlang/phobos/7693?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by BBasile** [comment]
ping @Bolpat. This is what happened in your tip phobos PR. I notify you from there not to pollute the review of your stuff.

**Comment by BBasile** [comment]
i can reproduce it locally with

- dscanner debug build
- config file with just if_else_same check enabled.

```bash
set -e

while true
do
	r=`dsc dlang/phobos/std/typecons.d -S --config=./dcanner.ini | grep Left`
	if [ ! -z "${r}" ]; then
		echo "managed to reproduce the issue..."
		echo $r
	break
	fi
done
```

The false positive only happens when building dscanner with `make debug` (named _dsc_ instead of _dscanner_), meaning that it may be a DMD backend bug.

@JinShil : another possible action in phobos right now is to use the release build of dscanner.

**Comment by BBasile** [comment]
It should be easy to digger it too now.

**Comment by BBasile** [comment]
Repro working on any linux machine:

```bash
set -e

if [ ! -d "D-Scanner" ]; then
	git clone https://github.com/dlang-community/D-Scanner.git
	cd "D-Scanner"
	git submodule update --init
else
	cd "D-Scanner"
fi

if [ ! -f "./dsc" ]; then
	make githash
	make debug
fi

if [ ! -f "./typecons.d" ]; then
	wget https://raw.githubusercontent.com/dlang/phobos/master/std/typecons.d
fi

while true
do
	r=`./dsc ./typecons.d -S | grep Left`
	if [ ! -z "${r}" ]; then
		echo $r
		break
	fi
done
```

**Comment by Hackerpilot** [comment]
Madness!

**Comment by BBasile** [comment]
The problem is reproducible when dparse logging is enabled. If `traceEnterAndExit` does nothing (aliases it to an empty string) then the false positive disappears. Also if  `mixin(traceEnterAndExit)` is commented in `parseOrOrExpression` then the problem goes away.

**Comment by BBasile** [comment]
Corruption happens in `parseType2`. This is a DMD bug so i close. A simplified case is [there](https://run.dlang.io/gist/c7bd67194938f8a3c325eb54599c97ac). Compare the results with and without the version defined in the DUB recipe. With verbose dparse you'll see stuff like

`is(T == ; U, U)` instead of `is(T == U, U)`

**Comment by JinShil** [comment]
> This is a DMD bug

Is there a DMD bugzilla issue?

**Comment by BBasile** [comment]
https://issues.dlang.org/show_bug.cgi?id=18941
