### ISSUE TITLE
Output option name in errors and warnings

### ISSUE THREAD

**Issue by Andy-FW** [dlang-community/D-Scanner#613]
Sometimes it could be hard to find out what checks one want to disable without studying the comments in the defaultConfig file or grepping the output message within the D-Scanner source code.

Therefore it would be very helpful, to include the name of the triggered check into the output message directly.

In addition, this would make it even easier to grep for specific errors or warnings.

**Comment by WebFreak001** [comment]
you can use the `--report` option to give you the keys if you only need it rarely

**Comment by BBasile** [comment]
The only viable option would be a 2 digits code: `[warn 00]: ...`, otherwise the message would be too polluted.

**Comment by Andy-FW** [comment]
This is now possible using 0.8.0.
