### ISSUE TITLE
0.5.x binaries: first.d:visit:327 Could not locate object.d or object.di

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/D-Scanner#614]
If I download a dscanner release binary: dscanner-v0.5.1-linux-x86_64.tar.gz (or 0.5.0), I get a bunch of warnings like:

> 2018-04-19T07:59:04.714:first.d:visit:327 Could not locate object.d or object.di

It happens if i run --styleCheck even on a file that contains only the ` module ...;` line.

The bug isn't reproducable with builds made with `dub build dscanner`.

**Comment by belka-ew** [comment]
LDC builds are affected (tested with 1.9.0)

**Comment by jmafc** [comment]
I'm seeing this using dscanner (version 0.5.6) built with ldc 1.8.0. The message appears only once, apparently when the first function is scanned (emits `Empty declaration` before the message if I place a lone semicolon before the function) and is followed by `Could not resolve location of module ...` for each of the imported modules. But if I use `-I` to indicate where the resolving paths are, the subject message is repeated almost endlessly (e.g., 148 times for a 105-line module).

**Comment by linkrope** [comment]
The `makefile` uses `-version=StdLoggerDisableWarning` as one of the `DMD_FLAGS`.
This explains that a `dscanner` you `make` yourself keeps quiet.
