### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/D-Scanner#627]
The current latest release doesn't build with dub on Windows, and its dependencies are out of date and incompatible with DCD. The [0.5.3 milestone](https://github.com/dlang-community/D-Scanner/milestone/10) also doesn't have any pending issues or pull requests.
Is there something specific that needs to be done before pushing a new patch release ?

**Comment by wilzbach** [comment]
> Is there something specific that needs to be done before pushing a new patch release ?

Nope. Just tagged 0.5.3 - the windows binary should be built automatically by Travis soon.
Check https://github.com/dlang-community/D-Scanner/releases/tag/v0.5.3 and https://travis-ci.org/dlang-community/D-Scanner/

I also invited you to the DCD/DScanner team, s.t. you can tag new patch releases in the future yourself whenever there's demand. Happy hacking!

**Comment by LaurentTreguier** [comment]
Thanks for the invitation (although I'll probably wait until I'm more familiar with things here before doing anything)

**Comment by LaurentTreguier** [comment]
Wait a minute. I didn't see that `0.5.3` had been tagged already 3 days ago because the latest "release" in the release section was `0.5.2`. And the dub package is also still at `0.5.2` instead of `0.5.3`, even 3 days after the tagging...
Dub packages are supposed to be automatically updated, yet `dscanner` hasn't been updated to `0.5.3` after 3 days. I am confused here, is this a dub registry bug, or is the automatic update somehow deactivated ?

**Comment by wilzbach** [comment]
> Dub packages are supposed to be automatically updated, yet dscanner hasn't been updated to 0.5.3 after 3 days. I am confused here, is this a dub registry bug, or is the automatic update somehow deactivated ?

Probably a bug in the dub-registry. Would be good to report it there.

**Comment by wilzbach** [comment]
>  I didn't see that 0.5.3 had been tagged already 3 days ago 

It wasn't. That's just the date of the last commit that the tag points too.

**Comment by LaurentTreguier** [comment]
Oh. Github has a somewhat strange way of displaying this...
