### ISSUE TITLE
no property statementNoCaseNoDefault for type const(WithStatement

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/D-Scanner#631]
Cannot build dscanner binary with dub.

```sh
dub fetch dscanner --version=0.5.3
dub run dscanner
```
Output:
> Building package dscanner in /home/belka/.dub/packages/dscanner-0.5.3/dscanner/
> Running pre-generate commands for dscanner...
> Performing "debug" build using /usr/bin/dmd for x86_64.
> stdx-allocator 2.77.1: target for configuration "library" is up to date.
> emsi_containers 0.8.0-alpha.7: target for configuration "unittest" is up to date.
> libdparse 0.8.5: target for configuration "library" is up to date.
> dsymbol 0.3.7: target for configuration "library" is up to date.
> inifiled 1.3.1: target for configuration "library-quiet" is up to date.
> libddoc 0.3.0-beta.1: target for configuration "lib" is up to date.
> dscanner 0.5.3: building configuration "application"...
> ../.dub/packages/dscanner-0.5.3/dscanner/src/dscanner/analysis/unused.d(314,18): Error: no property statementNoCaseNoDefault for type const(WithStatement)
> /usr/bin/dmd failed with exit code 1.

```
dub --version
DUB version 1.9.0, built on May  1 2018

DMD64 D Compiler v2.080.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

**Comment by BBasile** [comment]
Try the same with 0.5.4 in ~30/45 mind. The problem is that the minor version of dparse and dsymbol should have been increased yesterday but instead the patch only has been increased, creating a breaking change.

**Comment by belka-ew** [comment]
Thx

**Comment by BBasile** [comment]
It's the less i could do since I was responsible for this backward breakage. Now 0.5.x is still broken up to 0.5.3. Fortunately people rarely fetch a particular version so they wont notice. :crossed_fingers:
