### ISSUE TITLE
Check for documented `throw` could also detect calls to `enforce`

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#635]

**Comment by WebFreak001** [comment]
hm this doesn't seem to be a good solution, when you have custom wrapper functions or aliases for enforce this will never trigger (for example enforceBadRequest in vibe.d), only covering a fraction of actual code. If the defined enforce function doesn't even throw anything it would even give false positives. Also what if ufcs is used? Maybe the object has a function called enforce which does something else. It should go recursively through all functions to find this out. Maybe something for DCD instead?

**Comment by BBasile** [comment]
It's not so different from what the check currently do.
