### ISSUE TITLE
Please update stx.allocator

### ISSUE THREAD

**Issue by JinShil** [dlang-community/D-Scanner#636]
[We are trying to remove the long-deprecated `std.c` namespace from phobos](https://github.com/dlang/phobos/pull/6515), but there are a few packages still depending on it indirectly due to https://github.com/dlang-community/stdx-allocator.  stdx-allocator was recently updated to remove the dependency, but DMD needs projects to update to the [latest release](https://github.com/dlang-community/stdx-allocator/releases) (2.77.2) to keep its CI functioning.

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6515/5/pipeline/231

**Comment by BBasile** [comment]
This will come in the following hour.

**Comment by BBasile** [comment]
D-Scanner is okay now but i see DCD needs the same kind of update. (dparse too but it's done)
