### ISSUE TITLE
Wrong version: --version outputs v0.5.5 instead of v0.5.6

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#648]
D-Scanner windows release v0.5.6 outputs version v0.5.5 instead of v0.5.6

**Comment by BBasile** [comment]
The windows version still uses a harcoded version number, so a smart fix to this would be to do like under posix for good.

**Comment by LaurentTreguier** [comment]
Wouldn't that be a matter of just removing `else version(Windows)` and `DEFAUULT_DSCANNER_VERSION` (and its ugly typo) from [`src/dscanner/dscanner_version.d`](https://github.com/dlang-community/D-Scanner/blob/master/src/dscanner/dscanner_version.d), and then adding `git describe --tags > githash.txt` in [`build.bat`](https://github.com/dlang-community/D-Scanner/blob/master/build.bat) ?

**Comment by wilzbach** [comment]
Should be fixed by https://github.com/dlang-community/D-Scanner/pull/650
