### ISSUE TITLE
Version naming inconsistency

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/D-Scanner#651]
After seeing #650, I noticed that the version from `dscanner --version` (or `dscanner.exe --version`) differs when compiling with make/build.bat and when compiling with dub.
The version extracted from git begins with "v" (e.g. `v0.5.6`) while the dub version doesn't (e.g. `0.5.6`). It's just a small inconsistency, I don't think it's a real problem, but I simply like consistency in general, which is why I'm posting this issue.

**Comment by wilzbach** [comment]
https://github.com/dlang-community/D-Scanner/pull/652
