### ISSUE TITLE
Weird false positive for infinite range check

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#653]
Happens in phobos, [see here](https://circleci.com/gh/dlang/phobos/8012?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

```
std/experimental/allocator/common.d(0:0)[warn]: Use `enum bool empty = false;` to define an infinite range.
```

Line and column are invalid and the file doesn't even contain any `bool empty();` function.

**Comment by BBasile** [comment]
@wilzbach, can you restart the CircleCI check in the PR referenced above ?

**Comment by wilzbach** [comment]
Wouldn't help as the DScanner version is pinned. I will do an update of the hash later today though.
