### ISSUE TITLE
Warn always about "implicit auto function"

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-Scanner#664]
You may wonder what the heck is that. Here is an _explicit auto function_:

```d
auto foo(){return 0;}
```

Here is an _implicit auto function_:

```d
@safe foo(T = int)()
{
    static if (is(T : int))
        return 0;
    else
        return "it's an auto func";
}
```

In D this is very easy to forget `void` when there are leading attributes. There 's already a check for the auto function (the explicit ones...) so this additional warn could be added there instead of a new check.

**Comment by LaurentTreguier** [comment]
Isn't it the opposite, the first one being the explicit ?...

**Comment by BBasile** [comment]
yeah, thanks.
