### ISSUE TITLE
Says line is longer than 120 columns when it's not

### ISSUE THREAD

**Issue by spikespaz** [dlang-community/D-Scanner#673]
I don't know why, but it says that the line is longer than it really is. Take a look at the screenshot below with rulers set up at 110 and 120 columns.

![image](https://user-images.githubusercontent.com/12502988/41935424-7d5d5b96-793e-11e8-9a78-797f8bc041ed.png)

**Comment by WebFreak001** [comment]
tabs?

**Comment by spikespaz** [comment]
@WebFreak001 Spaces. But what does that have to do with this?

**Comment by spikespaz** [comment]
@WebFreak001 I'm sorry to be crating so many issues. You've probably seen my name a lot recently, I've been having a lot of problems with code-d.

**Comment by BBasile** [comment]
Can you quote the full line so that the problem can be analyzed. You picture is actually of no help.

**Comment by spikespaz** [comment]
I can't remember what the line was. I already rewrote that section. It was pobably something as follows:

```d
        registerHandler(filePath, engineName, engineURL, browserName, engines[engineName]);
```

**Comment by BBasile** [comment]
Cant reproduce.

**Comment by Hackerpilot** [comment]
Please copy/paste text into your bug reports. We really can't use screen shots of your text editor to accomplish anything.
