### ISSUE TITLE
False positive for redundant attributes (__gshared static in struct)

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/D-Scanner#675]
```d
__gshared static int a;
```

falsely gets marked as redundant. Even though when running this code:
```d
import core.thread;
import std.stdio;

static int a;
void main() {
  a = 4;
  new Thread({ writeln(a); }).start();
}
```

it will print 0 because a isn't __gshared.

**Comment by wilzbach** [comment]
static is still redundant. That's what the check is about.

**Comment by BBasile** [comment]
That's debatable since `__gshared` is two things. Maybe the check could say that in this case that `static` which is superfluous.

**Comment by WebFreak001** [comment]
oh yeah ok sorry, but it also happens in a struct:
```d
struct S {
  __gshared static int a;
}
```

here it is not redundant

**Comment by ZombineDev** [comment]
@WebFreak001 it is still redundant as `__gshared` always has the meaning of a application global (not instance) storage class: https://run.dlang.io/gist/2294c232b2c9380f98feae03700f9139

**Comment by WebFreak001** [comment]
oh ok TIL
