### ISSUE TITLE
Add unique error and warning labels

### ISSUE THREAD

**Issue by Voultapher** [dlang-community/D-Scanner#687]
Right now when running dscanner it reports something like this:
```
main.d(6:25)[warn]: Public declaration 'fill_linear_n' is undocumented.
main.d(10:14)[warn]: Variable `i` initializer is useless because it does not differ from the default value
main.d(18:8)[warn]: Public declaration 'fill_linear_n_lookup_one' is undocumented.
```
Warning 1 and 3 are fairly straight forward, and I can address them by searching `dlang function documentation`. Yet the second warning leaves me hanging telling me what is wrong, yet I have no idea how to fix it, because searching for it is not conclusive.

To help with this issue most linters I know employ a form of short unique label for each error and warning.

Either with an abstract symbol like: `E112` or `W601`
Examples:
- [pycodestlye](http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)
- [pyflakes](https://lintlyci.github.io/Flake8Rules/)

Another popular option is to use a short unique description like: `no-duplicate-case` or `borrowed_box`
Examples:
- [eslint](https://eslint.org/docs/rules/)
- [clippy](https://rust-lang-nursery.github.io/rust-clippy/master/index.html)

Ideally there is an overview page like in the examples that is SEO optimized and that holds both explanation and possible resolution.

Searching for `dscanner W226` or `dscanner no-duplicate-case` is **much** easier and more likely to lead to the place explaining the rule and how to fix code affected by it.

**Comment by BBasile** [comment]
This was suggested [here too](https://github.com/dlang-community/D-Scanner/issues/613#issuecomment-381963462). Now the point is to have the rationale linked to the warning number. About that I like the doc of pyflakes and Clippy and i'd be in favor of making something similar for D-Scanner. If anyone is talented at making GH pages then start something (unless someone is against the idea, which would be surprising.

**Comment by Voultapher** [comment]
For the record, after some more staring at the warning I figured out how to address it, discouraging an explicit initialisier is questionable imo, even the dlang tour does it that way: https://tour.dlang.org/tour/en/basics/loops.

**Comment by wilzbach** [comment]
I think the two points to take away here are:
- use errors codes (I really like shellcheck's wiki, e.g. https://github.com/koalaman/shellcheck/wiki/SC1004)
- don't activate the "useless initializer" check by default (as it's a very subjective choice and not recommended/activated for DMD/Phobos either)

> discouraging an explicit initialisier is questionable imo

FWIW the check is only when you initialize to the default value. Floating point types have NaN as default init value, so the explicit initializer isn't explicit at the tour, but required.

**Comment by BBasile** [comment]
I thought it was about making a github website with the rationales.

**Comment by Voultapher** [comment]
This issue hasn't see any activity in years, so I'm closing it.
