### ISSUE TITLE
`do` exptected after InStatement or OutStatement

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/D-Scanner#692]
```shell
$ cat test.d 
interface I
{
    void func()
    in
    {
    }
}
```

> test.d(7:1)[error]: `do` exptected after InStatement or OutStatement
> test.d(7:1)[error]: Expected `}` instead of `EOF`
> test.d(1:11)[warn]: Public declaration 'I' is undocumented.

```shell
$ ~/.dub/packages/dscanner-0.5.9/dscanner/bin/dscanner --version             
v0.5.9
```

**Comment by BBasile** [comment]
dparse-side fix is ready for review https://github.com/dlang-community/libdparse/pull/270

**Comment by belka-ew** [comment]
Thanks
