### ISSUE TITLE
Illegal instruction when checking anonymous class

### ISSUE THREAD

**Issue by linkrope** [dlang-community/D-Scanner#697]
```d
auto foo()
{
    return new class Bar {};
}
```
With dscanner-v0.5.10-linux-x86_64.tar.gz running `dscanner --styleCheck` crashes:
```
Illegal instruction
```

**Comment by BBasile** [comment]
This is actually a failed assertion in D-Symbol

**Comment by BBasile** [comment]
I will add full support for anonymous class completion, which will fix this as a bonus.
