### ISSUE TITLE
Pin libdparse to a specific version

### ISSUE THREAD

**Issue by 0xEAB** [dlang-community/D-Scanner#706]
*I'm aware that this idea is pretty controversial.*

I think it would be better, if `D-Scanner` & co pinned the `libdparse` dependency to one specific version instead of `~>`.

I must admit the current state of affairs is totally fine by the idea of semver. And also library-wise there isn't really a problem. The pitfall is the problem that occurs for users of those tools when same patch accidentally breaks some functionality.

#### Let me explain this on a real situation I faced:
I saw a new version of (I think it was) `DCD v0.9.11` had been released. I did a last `dcd-server --version` and wrote down the old version just in case the new update would turn into a 2-headed monster later... Well, guess what? It did.
No problem, I thought, deleted all DUB-related files and did a `git checkout vM.m.p` and built that old version again. Suprise, surprise - also this version started to behave weird. So I started thinking about what was going on, and came to the conclusion that some "innocuous" libdparse update has broken it.

I could have now traced back which version I could possible and perhaps used to build DCD (or whatever app it was) maybe. But I don't think that this is the proper solution. (By the way, with the latest version everything is working fine).

#### Findings
It are not only tools like DCD themselves getting defected by this, apps that depend on them will suffer from this, too. To give an example, I've built the same version of `serve-d` (utilizes `D-Scanner` and `dfmt`) two times (each time with a different version of libdparse thanks to `~>`). The first time, everything worked fine, the 2nd time it suffered from some bad patch (I guess the same one that made DCD struggle) and had weird crashes...

Having libdparse pinned to a specific version, one could safely build a specific version of D-Scanner without having to fear that it now won't work for whatever.

**Comment by LaurentTreguier** [comment]
From my point of view, application should pin versions, while libraries should be more flexible, and use `~>`.
DCD, dfmt, and D-Scanner can all be used as both. A solution would be to have separate configurations for the 2 cases (just like it was proposed in #705).
The `application` configuration would have pinned versions of libraries (and use the `preGenerateCommand` for automatic versioning), and the `library` configuration would still use `~>` (and no `preGenerateCommand`).

**Comment by WebFreak001** [comment]
we got dub.selections.json here now, so dependencies are pinned. serve-d also uses selections now.
