### ISSUE TITLE
`is(E1 == __vector)` errors but DMD accepts

### ISSUE THREAD

**Issue by thewilsonator** [dlang-community/D-Scanner#716]
https://github.com/dlang/phobos/pull/6776

```d
auto cmp(R1, R2)(R1 r1, R2 r2)
 if (isInputRange!R1 && isInputRange!R2)
 {
     version (BigEndian)
         enum endianForMemcmp = true;
     else
         enum endianForMemcmp = ElementEncodingType!R1.sizeof == 1;

     static if (endianForMemcmp
         && isDynamicArray!R1 && isDynamicArray!R2
         && is(R1 : E1[], E1) && is(R2 : E2[], E2) // just to get E1 & E2
         && __traits(isUnsigned, E1) && __traits(isUnsigned, E2)
         && E1.sizeof == E2.sizeof
         && (is(Unqual!E1 == char) == is(Unqual!E2 == char)) // Auto-decoding needs to match.
         && !is(Unqual!E1 == wchar) && !is(Unqual!E2 == wchar) // Can't memcmp UTF-16 to get order.
         && !is(E1 == __vector) && !is(E2 == __vector)) // ERROR
```

the error is 
```
std/algorithm/comparison.d(625:56)[error]: Expected `(` instead of `)`
std/algorithm/comparison.d(625:56)[error]: Primary expression expected
```

**Comment by BBasile** [comment]
It's a dparse bug related to the fact that it accepted basic types as primary expression. Something special has to be done for vector since apparently both form (with parens and parens-less) are valid, which, i confess, was not aware of.

**Comment by thewilsonator** [comment]
I presume its to do with the parser getting confused between the `is(name == keyword)` form and the `is(name == type, dependant, args)` for for which `__vector` falls into both.

**Comment by thewilsonator** [comment]
From the linked PR, I presume its expecting the form `!is(E1 == __vector(T1[N1),T1,N1) && !is(E2 == __vector(T2[N2),T2,N2))`.

**Comment by thewilsonator** [comment]
Anyway please migrate this issue if it belongs to parse instead.

**Comment by BBasile** [comment]
The situation is bad in that it wont be fixed today. The bug is **still** in dparse ~master but the pull request that adapts D-Scanner to dparse ~master is not yet merged (#713).

**Comment by BBasile** [comment]
The fix is now part of the PR mentioned previously.

**Comment by BBasile** [comment]
Although fixed now it's not yet effective in phobos.

**Comment by thewilsonator** [comment]
Thanks!
