### ISSUE TITLE
unused_variable_check should ignore declarations without a body

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-Scanner#727]
e.g.

```
std/windows/charset.d(33:45)[warn]: Parameter s is never used.
std/windows/syserror.d(32:15)[warn]: Parameter errCode is never used.
```

That looks like sth. that could be fixed on the Dscanner side too as the never-used check should ignore declarations without a body.

There are a few modules in Phobos that can be removed from the selective filtering after this has been fixed.

See also: https://github.com/dlang/phobos/pull/6783

**Comment by BBasile** [comment]
closed by #728
