### ISSUE TITLE
Support for Jenkins CI plugin "Warnings Next Generation Plugin"

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#732]
Jenkins CI has created a new plugin Warnings Next Generation Plugin (https://wiki.jenkins.io/display/JENKINS/Warnings+Next+Generation+Plugin) which supersedes a lot of the existing code scanner plugins. There is already support for almost 100 different formats (https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md)

Adding support for D-Scanner would be great.

**Comment by andre2007** [comment]
Also issue for Jenkins CI group created:
https://issues.jenkins-ci.org/browse/JENKINS-55051

**Comment by BBasile** [comment]
How new linters are added over there ? Is this community driven ?

**Comment by andre2007** [comment]
As far as I understood, they accept community pull requests. Main part of the work would be to copy this file https://github.com/jenkinsci/analysis-model/blob/507a04bcd0c7f0958c62611ded361819f10d778e/src/main/java/edu/hm/hafner/analysis/parser/SonarQubeParser.java and make small adaptions.

D-Scanner at the moment does not have issue severity/priority. Maybe this could be determined by the key:
dscanner.**suspicious**.unmodified -> warning
dscanner.**style**.alias_syntax -> info

But in general it seems, most linter have a priority/severity. dscanner --report , could already contain such a field. Also the module name (``` module abc.def;```) might be an interesting field which could be returned by --report. Whether this is needed for the Jenkins CI plugin I am not 100% sure.

**Comment by andre2007** [comment]
D-Scanner support was merged into Jenkins plugin.
