### ISSUE TITLE
Add additional json report for SonarQube

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#746]
With SonarQube 7.2 a generic issue reporter was added to SonarQube. 

By providing the issues in their JSON format no additional D Language plugin is needed.
The idea is to enhance dscanner arguments like this:
```dscannner --report --reportFormat sonarqube-generic .```

This will generate the JSON 

```
{ "issues": [
    {
      "engineId": "dscanner",
      "ruleId": "rule1",
      "severity":"BLOCKER",
      "type":"CODE_SMELL",
      "primaryLocation": {
        "message": "fully-fleshed issue",
        "filePath": "sources/a.d",
        "textRange": {
          "startLine": 30,
          "endLine": 30,
          "startColumn": 9,
          "endColumn": 14
        }
      },
      "effortMinutes": 90,
      "secondaryLocations": [
        {
          "message": "cross-file 2ndary location",
          "filePath": "sources/b.d",
          "textRange": {
            "startLine": 10,
            "endLine": 10,
            "startColumn": 6,
            "endColumn": 38
          }
        }
      ]
    },
    {
      "engineId": "dscanner",
      "ruleId": "rule2",
      "severity": "INFO",
      "type": "BUG",
      "primaryLocation": {
        "message": "minimal issue raised at file level",
        "filePath": "sources/measure.d"
      }
    }
]}
```

More details
https://www.sonarqube.org/sonarqube-7-2/
https://docs.sonarqube.org/latest/analysis/generic-issue/

**Comment by BBasile** [comment]
I'd suggest you to try to implement the feature since very few people use SonarQube. If i remember correctly a previous conversation about reports, one problem is that D-Scanner message are not well classified.

**Comment by andre2007** [comment]
Yes, that is the plan :)
I already plan to add some classification. See here my work on this topic:
https://github.com/dlang-community/D-Scanner/compare/master...andre2007:metadata

**Comment by WebFreak001** [comment]
I like this, I had evaluated SonarQube before because it looked good, but went for something else instead for C. However if you search for test integrations with D I think it's great having support for this.

**Comment by andre2007** [comment]
PR https://github.com/dlang-community/D-Scanner/pull/747
