### ISSUE TITLE
False positive on "unused variable" with side effect

### ISSUE THREAD

**Issue by Geod24** [dlang-community/D-Scanner#762]
```D
private:
class Identity { string val; }
Identity[string] arr;

void main ()
{
    arr["Hello"] = new Identity;
    oops();
}

void oops ()
{
    auto v = "Hello" in arr;
    v.val = "Side effect";
}
```

```console
dscanner --styleCheck test.d
test.d(13:10)[warn]: Variable v is never used.
```

This prevents this check from being enabled in DMD, as it relies heavily on this pattern.

**Comment by Basile-z** [comment]
There's a strange bug. When the unary for `v` is visited, its nested unary, the one for `val`, is `null`.

https://github.com/dlang-community/D-Scanner/blob/e5a73fa0ef0bf790a56fbcb34df407878454c965/src/dscanner/analysis/unused.d#L200-L206
