### ISSUE TITLE
Disable unused parameters check

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/D-Scanner#765]
Unused parameters check is actually harmful, because unused parameters are often useful. I’d like to propose not to check the parameters or at least make it independent from “unused_variable_check”.

## Rationale

1. In class hierarchies it is possible that the base class defines parameters that aren’t used by the class but can be used by its children.
```d
class C
{
    void myfunc(int id)
    {
    }
}
```

2. For structs and functions some template may rely on a specific signature, even if the function itself doesn’t use all parameters.

The way to fix it, is to skip the parameter name:

```d
void func(string, string) {}
```

But this breaks the documentation. Without meaningful parameter names I can’t see anymore what the parameters are supposed to be. So I would rather write

```d
void func(string id, string language) {}
```

even if the parameters aren’t used.

Furthermore I can’t document parameters anymore since “Params” in Ddoc refers to parameter names.

**Comment by wilzbach** [comment]
> I’d like to propose not to check the parameters or at least make it independent from “unused_variable_check”.

I strongly argue against removing it entirely. Seperate check is a good idea though.

**Comment by Basile-z** [comment]
Yes split and subclass.

**Comment by belka-ew** [comment]
Just for info, I'm going to work on it (splitting the checks) next week.
