### ISSUE TITLE
mismatched_args_check: Line 18446744073709551615

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#774]
Checking the file https://github.com/adamdruppe/arsd/blob/master/vorbis.d will produce following finding:

```
{
      "key": "dscanner.confusing.argument_parameter_mismatch",
      "name": "mismatched_args_check",
      "fileName": "./gen/tmp/user.home/dub/packages/arsd-official-3.0.1/arsd-official/vorbis.d",
      "line": 18446744073709551615,
      "column": 18446744073709551615,
      "message": "Argument 5 is named 'n', but this is the name of parameter 1"
    }
```

The line and columns  are wrong and causing and JSONException while trying to get them using ```.integer```

**Comment by Hackerpilot** [comment]
Looks like `size_t.max`. Could be either a bug in the lexer or a bug in the argument check.
