### ISSUE TITLE
false positive in style checker, checking casts

### ISSUE THREAD

**Issue by berni44** [dlang-community/D-Scanner#781]
The following unittest (in std.format) was rejected by the style checker:

```D
@safe pure unittest
{
    enum A { one, two, three }
    
    string t2 = format("[%10s] [%-10s]", cast(A) 10, cast(A) 10);
    assert(t2 == "[ cast(A)10] [cast(A)10 ]");
}
```

The problem is the `cast(A)10` inside the string.

**Comment by Hackerpilot** [comment]
I just built D-Scanner from source and ran it on that code snippet with all checks enabled. The only message that I got was `test.d(6:5)[warn]: An assert should have an explanatory message`. Is that what you're talking about?

**Comment by berni44** [comment]
No. The snippet is taken from Phobos, currently line 4542. When I run 

make -f posix.mak style

I get the following message:

Enforce space after cast(...)
grep -nrE '[^"]cast\([^)]*?\)[[:alnum:]]' $(find etc std -name '*.d') ; test $? -eq 1
std/format.d:4542:    assert(t2 == "[ cast(A)10] [cast(A)10 ]");

I asked, where to report this bug and was first pointed to bugzilla, and there someone said, I should post it here... But maybe it's still the wrong place...

**Comment by Hackerpilot** [comment]
That line of the makefile isn't even calling `dscanner`. It's calling `grep`. Who asked you to report this here? I think they're confused.

**Comment by PetarKirov** [comment]
Hi @berni44 I hoped I haven't confused you. The only line of code that needs fixing is the grep regex here:
https://github.com/dlang/ci/blob/b07daedab610bb397cc623a48887a44ddbd1de6d/buildkite.sh#L110

**Comment by berni44** [comment]
@PetarKirov So it should actually be a phobos bugreport? (I don't know, how to fix that line.)

@Hackerpilot Seb pointed me here: https://issues.dlang.org/show_bug.cgi?id=20343

**Comment by PetarKirov** [comment]
Yes. I guess Seb didn't see the error message and assumed that the error was coming from DScanner, while it's just the grep line from the `posix.mak` file.
