### ISSUE TITLE
`dscanner.suspicious.local_imports` is invalid

### ISSUE THREAD

**Issue by Geod24** [dlang-community/D-Scanner#808]
Now that the compiler does a two-phases lookup, this warning message is not correct anymore, local symbols cannot be hidden by `import` (unless it's selective).

**Comment by WebFreak001** [comment]
issue still persists: https://run.dlang.io/is/H4zWiM

**Comment by Geod24** [comment]
> nvm but now it seems like it is the other way around, making it also confusing

What you're seeing is expected behavior. If you change the local import to `import std.stdio : writeln;` in `main` it'll call it (because it's essentially creating a local `alias`).

We use `import std.algorithm`, and some project-specific imports in `unittest` blocks a lot and this warning is plain annoying. It would force us to use module-global `version (unittest)` imports to achieve what we want to do (avoid bringing in unneeded dependencies for a module).

**Comment by Hackerpilot** [comment]
I'm more in favor of getting rid of this warning, or at least disabling it by default. It was introduced to work around a problem in earlier versions of the compiler and it now only applies to people using those old compilers.

**Comment by Hackerpilot** [comment]
@Geod24 Do you consider this resolved?

**Comment by Geod24** [comment]
Works for me, thanks!

**Comment by WebFreak001** [comment]
I think we should revert this, the spec says it's still how it was before, so I think this could rather be called a regression in the compiler: https://dlang.org/spec/module.html#scoped_imports

**Comment by Geod24** [comment]
The spec is wrong. If you test that snippet of code, it doesn't print anything.

**Comment by WebFreak001** [comment]
Is there some changelog entry related to that? If the spec was kept I would rather call it a compiler regression imo.

**Comment by Geod24** [comment]
Unfortunately, changes in the compiler always precede changes in the spec.
That change was done a long time ago (https://github.com/dlang/dmd/pull/5445).
It was part of the overall effort to change protection to visibility, and very much wanted, so *definitely* not a regression.

**Comment by Hackerpilot** [comment]
It looks like another case where we just need to make a pull request to the language specification.
