### ISSUE TITLE
Replace rdmd with dub?

### ISSUE THREAD

**Issue by andre2007** [dlang-community/D-Scanner#821]
As DMD x86_64 does not have a rdmd x86_64 executable, I see the error message `rdmd is not recognized as internal or external command` while building dscanner dub package. (I only have bin64 folder in PATH environment variable).

I wonder whether we can replace rdmd with a single file dub package.
https://github.com/dlang-community/D-Scanner/blob/2963358eb4a24064b0893493684d4075361297eb/dub.json#L27

Quickfix is of course adding `bin` folder to PATH or copying `rdmd` into folder `bin64`. (Also created a request to include x86_64 bit version of rdmd into DMD windows package).

**Comment by PetarKirov** [comment]
It should be possible to replace `rdmd file.d` with `dmd -run file.d` (or `dmd -i -run file.d` if `file.d` imports other files in the repo).
The main benefit of `rdmd` over `dmd -run` is that it caches the compilation output, but if you're running a file for the first time `dmd -run` is faster.

**Comment by PetarKirov** [comment]
I think we should built-in support to dub for running D script files as build commands. Then dub can manage the compilation artifacts cache, and also allow users to write simpler and more portable code.

**Comment by andre2007** [comment]
@PetarKirov 
Yes, built in support for dub sounds great.

dmd -run is unfortunately not working (ldc/gdc)
