### ISSUE TITLE
Build failure when compiling for Homebrew on Linux

### ISSUE THREAD

**Issue by p-linnane** [dlang-community/D-Scanner#884]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While trying to package v0.13.0 we are running into a build error on Linux. The relevant GitHub Actions run can be found [here](https://github.com/Homebrew/homebrew-core/actions/runs/3852640661/jobs/6564985752).

The error in question:

```
/usr/bin/ld: obj/dmd/containers/src/containers/ttree.o: relocation R_X86_64_32 against hidden symbol `__stop_minfo' can not be used when making a PIE object
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

Any guidance here would be appreciated. Thank you!

**Comment by rikkimax** [comment]
Shouldn't this be PIC?

**Comment by p-linnane** [comment]
Thank you. I was able to get it to build with `ENV.append "DFLAGS", "-fPIC" if OS.linux?`.

**Comment by rikkimax** [comment]
This isn't the first report of this release having issues with PIC not
being set. I should probably look into what happened.

**Comment by rikkimax** [comment]
Ah huh! You weren't using dub, that explains it. Dub is setup to handle this.
