### ISSUE TITLE
Discarded return value warning does not work for aliased types

### ISSUE THREAD

**Issue by zyedidia** [dlang-community/D-Scanner#885]
If a type is aliased, using a static method on the aliased type does not generate a warning if the return value is discarded:

```d
struct Foo {
    static bool val() {
        return false;
    }
}

alias X = Foo;

void main() {
    Foo.val(); // warning
    X.val();   // no warning
}
```

**Comment by WebFreak001** [comment]
looks like an alias issue in dsymbol, see https://github.com/dlang-community/DCD/issues
