### ISSUE TITLE
[warning] first.d:visit Could not resolve location of module ...

### ISSUE THREAD

**Issue by linkrope** [dlang-community/D-Scanner#903]
I have no idea what's wrong with the import path: I'm getting lots of these warnings lately.

See: https://github.com/linkrope/gamma/actions/runs/5192881661/jobs/9362664165
    > Check Style

**Comment by WebFreak001** [comment]
fixed in master, but needs a release. This was just something that changed in std.experimental.logger with a compiler update

**Comment by linkrope** [comment]
Funny: so the warnings are even irrelevant for D-Scanner!
I found out that I can get rid of them by explicitly specifying the import paths (-I),

**Comment by WebFreak001** [comment]
theoretically they can be relevant, e.g. for the argument name check that will check for correct argument order - that check needs to look up the method, so if it can't find it (due to misconfigured imports and it being defined in a separate file), it would never trigger.

**Comment by WebFreak001** [comment]
fixed on 0.15.0
