### ISSUE TITLE
Support additional themes for HTML highlighting

### ISSUE THREAD

**Issue by snprajwal** [dlang-community/D-Scanner#924]
Currently, the HTML highlighting supports only Solarized Dark, and is hardcoded here: https://github.com/dlang-community/D-Scanner/blob/a958f9ac7b1654cde0e15689fc9c60623b55e6ce/src/dscanner/highlighter.d#L24

We can provide a `--theme` flag that allows users to pick from a small predefined set of themes. If anything, it provides an alternative to those who dislike Solarized Dark :P.

Would a PR be accepted for this?

**Comment by WebFreak001** [comment]
sure, I'm not sure how many people actually use this feature anyway, go wild with PRs.
