### ISSUE TITLE
Respect `excludedSourceFiles` when scanning sources

### ISSUE THREAD

**Issue by chances** [dlang-community/D-Scanner#932]
My project interops with C and GLFW writes a lot of intermediate files with the `*.d` extension.

D-Scanner ought ignore files included in Dub's `excludedSourceFiles`.

**Comment by WebFreak001** [comment]
D-Scanner is completely unrelated to DUB and this would be way out of scope, either specify the list of files you want to scan manually (e.g. using a shell script) or you could make a PR if you want some `--exclude` CLI argument that you can pass globs to ignore to.

**Comment by WebFreak001** [comment]
I saw now in your PR that you probably want this with `dub lint`, in that case this is an issue on the DUB side that is invoking D-Scanner

**Comment by chances** [comment]
See https://github.com/dlang/dub/issues/2700.

Thank you for reporting this issue, @WebFreak001.

**Comment by WebFreak001** [comment]
sure that would be fine
